#!/bin/bash
# For a simple text file upload (new file only)
curl -X PUT \
  -H "Authorization: token ${GITHUB_PAT}" \
  -H "Content-Type: application/json" \
  -d '{
    "message": "Auto-commit: HTML files generated by multi-agent system",
    "content": "'$(base64 -w 0 /app/index.html)'"
  }' \
  "https://api.github.com/repos/${GITHUB_USERNAME}/automatic-happiness/contents/index.html"
  